version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: aws-spring-boot-native-dsql-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"